name: my_environment3

channels:  
  - defaults
  - pytorch
dependencies:
  - pip=21.1.3
  - pytorch=1.11.0
  - python=3.8.10
  - pip:
    - transformers==4.30.2
    - scipy==1.10.1
    - scikit-learn==0.24.2

